version: '3.4'

networks:
  default:
    driver: bridge
volumes:
  kong-datastore:
  elasticsearch:

services:
  kong-db:
    image: postgres
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "15432:5432"
    env_file:
      - kong/.env
  kong:
    build: kong
    networks:
      - default
    env_file:
      - kong/.env
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
      - "8002:8002" # Admin API
  api:
    build: api
    networks:
      - default
    volumes:
      - ./api/:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  keycloak-db:
      image: postgres
      env_file:
        - authentication/.env
      networks:
        - default
      ports:
        - "25432:5432"

  keycloak:
      build:
        context: authentication
        dockerfile: Dockerfile
      env_file:
        - authentication/.env
      networks:
        - default
      ports:
      - "8080:8080"

  nginx:
    build:
      context: proxy
      dockerfile: Dockerfile
    volumes:
      - ./front/dist/:/etc/nginx/html/dist/
      - ./proxy/data/nginx/:/etc/nginx/conf.d
    networks:
      - default
    ports:
      - 7777:7777


  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - default

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - default
    depends_on:
      - elasticsearch
